import React from 'react';

const MetaHead = () => {
    return (
        <head>
            <title>Fin Test</title>
            <meta name="description" content="Generated by create next app"/>
            <link rel="icon" href="/favicon.ico"/>
        </head>
    )
}

export default MetaHead;